# Generated by Django 3.0.4 on 2020-05-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordforrad',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('norwegian', models.CharField(max_length=200, unique=True)),
                ('english', models.CharField(max_length=200)),
                ('usage_fr', models.IntegerField()),
                ('usage_permll', models.FloatField()),
            ],
        ),
    ]
