# Generated by Django 3.0.4 on 2020-05-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordforrad',
            name='lvl_usage',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20),
        ),
        migrations.AddField(
            model_name='ordforrad',
            name='word_class',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective')], max_length=20),
        ),
        migrations.CreateModel(
            name='VerbsFeatures',
            fields=[
                ('verb_id', models.AutoField(primary_key=True, serialize=False)),
                ('valency', models.IntegerField()),
                ('multi_world', models.BooleanField(verbose_name='multi world phrase')),
                ('norwegian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.Ordforrad')),
            ],
        ),
        migrations.CreateModel(
            name='NounsFeatures',
            fields=[
                ('noun_id', models.AutoField(primary_key=True, serialize=False)),
                ('plural', models.BooleanField(verbose_name='used in plural')),
                ('mass_noun', models.BooleanField()),
                ('norwegian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.Ordforrad')),
            ],
        ),
    ]
