# Generated by Django 3.0.4 on 2020-05-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_auto_20200522_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbsfeatures',
            name='norwegian',
        ),
        migrations.DeleteModel(
            name='NounsFeatures',
        ),
        migrations.DeleteModel(
            name='Ordforrad',
        ),
        migrations.DeleteModel(
            name='VerbsFeatures',
        ),
    ]
