# Generated by Django 3.0.4 on 2020-05-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarjetas', '0003_auto_20200522_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordforrad',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('norwegian', models.CharField(max_length=200, unique=True)),
                ('english', models.CharField(max_length=200)),
                ('word_class', models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective')], max_length=20)),
                ('lvl_usage', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('usage_fr', models.IntegerField()),
                ('usage_permll', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VerbsFeatures',
            fields=[
                ('verb_id', models.AutoField(primary_key=True, serialize=False)),
                ('valency', models.IntegerField()),
                ('multi_world', models.BooleanField(verbose_name='multi world phrase')),
                ('norwegian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.Ordforrad')),
            ],
        ),
        migrations.CreateModel(
            name='NounsFeatures',
            fields=[
                ('noun_id', models.AutoField(primary_key=True, serialize=False)),
                ('plural', models.BooleanField(verbose_name='used in plural')),
                ('mass_noun', models.BooleanField()),
                ('norwegian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.Ordforrad')),
            ],
        ),
    ]
